// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "ygang.top/gin-template/internal/config"

const TableNameSysUser = "sys_user"

// SysUser 系统用户
type SysUser struct {
	UserID     string       `gorm:"column:user_id;type:varchar(36);primaryKey;comment:用户 id" json:"user_id"`         // 用户 id
	UserName   *string      `gorm:"column:user_name;type:varchar(255);comment:用户名" json:"user_name"`                 // 用户名
	Password   *string      `gorm:"column:password;type:varchar(255);comment:密码" json:"password"`                    // 密码
	UpdateTime *config.Time `gorm:"column:update_time;type:datetime;autoUpdateTime;comment:更新时间" json:"update_time"` // 更新时间
	CreateTime *config.Time `gorm:"column:create_time;type:datetime;autoCreateTime;comment:创建时间" json:"create_time"` // 创建时间
	Remark     *string      `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                        // 备注
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
