server:
  port: 8080

mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 60

redis:
  host: localhost
  port: 6379
  db: 1
  key_prefix: gin-template