server:
  port: 8080
  auth:
    header: Authorization
    token_expired: 30
    exclude_urls:
      - /sys_user/login

mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 60

redis:
  host: localhost
  port: 6379
  db: 0
  key_prefix: gin-template