// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"ygang.top/gin-template/internal/config"
	"ygang.top/gin-template/internal/database"
	"ygang.top/gin-template/internal/engine"
	"ygang.top/gin-template/internal/engine/api_v1"
	"ygang.top/gin-template/internal/handler"
	"ygang.top/gin-template/internal/service"
)

// Injectors from wire.go:

func InitApplication() *gin.Engine {
	applicationConfig := config.InitApplicationConfig()
	db := database.NewDB(applicationConfig)
	query := database.NewQuery(db)
	sysUserService := service.NewSysUserService(query)
	sysUserHandler := handler.NewSysUserHandler(sysUserService)
	routes := api_v1.NewRoutes(sysUserHandler)
	ginEngine := engine.NewEngine(routes, applicationConfig)
	return ginEngine
}
