// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"ygang.top/gin-template/internal/config"
	"ygang.top/gin-template/internal/dao"
	"ygang.top/gin-template/internal/database"
	"ygang.top/gin-template/internal/engine"
	"ygang.top/gin-template/internal/engine/middleware"
	"ygang.top/gin-template/internal/engine/v1"
	"ygang.top/gin-template/internal/handler"
	"ygang.top/gin-template/internal/service"
	"ygang.top/gin-template/internal/utils"
)

// Injectors from wire.go:

func InitApplication() *gin.Engine {
	applicationConfig := config.InitApplicationConfig()
	db := database.NewDB(applicationConfig)
	sysUserDao := dao.NewSysUserDao(db)
	client := database.NewRedisClient(applicationConfig)
	redisClient := utils.NewRedisClient(client, applicationConfig)
	sysUserService := service.NewSysUserService(sysUserDao, redisClient, applicationConfig)
	sysUserHandler := handler.NewSysUserHandler(sysUserService)
	routes := v1.NewRoutes(sysUserHandler)
	errorHandleMiddleware := middleware.NewErrorHandleMiddleware()
	authMiddleware := middleware.NewAuthMiddleware(applicationConfig, redisClient)
	ginEngine := engine.NewEngine(routes, applicationConfig, errorHandleMiddleware, authMiddleware)
	return ginEngine
}
